project_name: netsuke

plugins:
  - import: github.com/goreleaser/goreleaser-rust@v1.6.0

# Ensure man pages exist before packaging. GoReleaser only archives files and
# fails later if they're missing, so fail fast with a helpful message instead.
before:
  hooks:
    - |
      test -f target/generated-man/netsuke.1 || {
        echo "::error title=Manpage missing::target/generated-man/netsuke.1 not found. Ensure build.rs or a dedicated step generates it before packaging.";
        exit 1;
      }

builds:
  # GoReleaser packages prebuilt Rust binaries. `skip_build: true` avoids
  # rebuilding and the `goos`/`goarch` matrix must mirror the CI build job
  # targets (linux/amd64, linux/arm64, darwin/amd64, darwin/arm64,
  # freebsd/amd64). Keep this list in sync with `.github/workflows/release.yml`.
  - id: netsuke
    binary: netsuke
    skip_build: true
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64


archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - target/generated-man/netsuke.1

nfpms:
  # Linux packages (deb/rpm) for netsuke
  - id: netsuke-packages
    package_name: netsuke
    vendor: "Netsuke"
    homepage: "https://github.com/leynos/netsuke"
    maintainer: "Payton McIntosh <pmcintosh@df12.net>"
    description: "Friendly build system that compiles structured manifests into a Ninja build graph"
    license: ISC
    formats: [deb, rpm]
    builds: [netsuke]
    bindir: /usr/local/bin
    contents:
      - src: ./target/generated-man/netsuke.1
        dst: /usr/local/share/man/man1/netsuke.1


# FreeBSD native .pkg via a post hook that runs only on FreeBSD.
# The GitHub Actions `package` job runs on Ubuntu, so CI produces only the
# tar.gz artefact unless a FreeBSD runner executes this configuration.
# This hook is a no-op on Linux and macOS CI runners.
# When run on FreeBSD it stages files and calls `pkg create`, yielding
#   dist/netsuke-<version>.pkg
# Requires `pkg` installed on the FreeBSD runner. The ABI string is derived at
# runtime to be accurate.
hooks:
  post:
    - |
      if [ "$(uname -s)" = "FreeBSD" ]; then
        set -euo pipefail
        trap 'rc=$?; rm -rf "$STAGE" manifest.ucl 2>/dev/null || true; exit $rc' EXIT
        VERSION="{{ .Version }}"
        ABI="$(pkg config ABI)"  # e.g., FreeBSD:14:amd64

        for BIN in netsuke; do
          STAGE="stage-${BIN}"
          MANPAGE="target/generated-man/${BIN}.1"
          rm -rf "$STAGE"
          install -d "$STAGE/usr/local/bin" "$STAGE/usr/local/share/man/man1"

          # Prefer the built artefact from dist; if not found, fall back to target/release
          # GoReleaser’s Rust plugin names artefacts predictably:
          #   dist/{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}/{{BIN}}
          # but picking from target/release is usually simpler on same-OS runners.
          if [ -x "target/release/${BIN}" ]; then
            install -s -m 0755 "target/release/${BIN}" "$STAGE/usr/local/bin/${BIN}"
          else
            echo "WARN: target/release/${BIN} not found; ensure the FreeBSD build ran."
            continue
          fi

          if [ -f "${MANPAGE}" ]; then
            install -m 0644 "${MANPAGE}" "$STAGE/usr/local/share/man/man1/${BIN}.1"
          fi

          cat > manifest.ucl <<UCL
name: "${BIN}"
version: "${VERSION}"
origin: "local/${BIN}"
comment: "Netsuke build system"
www: "https://github.com/leynos/netsuke"
maintainer: "Payton McIntosh <pmcintosh@df12.net>"
arch: "${ABI}"
desc: "Friendly build system that compiles structured manifests into a Ninja build graph."
licenses: ["ISC"]
UCL

          mkdir -p dist
          pkg create -r "$STAGE" -M manifest.ucl -o dist
          rm -rf "$STAGE" manifest.ucl
          trap - EXIT
        done
      fi

release:
  github:
    owner: leynos
    name: netsuke
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'
      - 'Merge pull request'
      - 'Merge branch'
