name: Export binary name
description: Derive the crate's binary name from Cargo.toml and export BIN_NAME
runs:
  using: composite
  steps:
    - name: Derive binary name
      shell: bash
      run: |
        set -euo pipefail
        toml_path="${CARGO_TOML_PATH:-Cargo.toml}"
        BIN_NAME="$(
          python3 - <<'PY' || echo ''
import os, tomllib
path = os.environ.get('CARGO_TOML_PATH', 'Cargo.toml')
with open(path, 'rb') as f:
    data = tomllib.load(f)
name = (data.get('package') or {}).get('name')
bins = [b.get('name') for b in data.get('bin', []) if 'name' in b]
print((bins[0] if bins else name) or '')
PY
        )"
        if [ -z "${BIN_NAME:-}" ]; then
          echo "::error title=Binary name not found::Set package.name or [[bin]] name in ${toml_path}"
          exit 1
        fi
        echo "BIN_NAME=$BIN_NAME" >> "$GITHUB_ENV"
