//! Real-Ninja runtime tests for serial dependency ordering.
//!
//! These tests drive an actual `ninja` process against a bundle generated by
//! `generate_bundle`, using filesystem markers to prove declaration order,
//! failure short-circuiting, and shared-work reuse. They deliberately assert
//! observable behaviour rather than generated text.

#![cfg(unix)]

use anyhow::{Context, Result, ensure};
use camino::Utf8PathBuf;
use cap_std::{ambient_authority, fs_utf8::Dir};
use netsuke::ast::{Recipe, StringOrList};
use netsuke::ir::{Action, BuildEdge, BuildGraph, DependencyOrder};
use netsuke::ninja_gen::generate_bundle;
use std::io::ErrorKind;
use std::process::Command;
use tempfile::TempDir;

const NINJA: &str = "ninja";

fn action(command: &str) -> Action {
    Action {
        recipe: Recipe::Command {
            command: command.into(),
        },
        description: None,
        depfile: None,
        deps_format: None,
        pool: None,
        restat: false,
    }
}

/// Construct an action whose dependencies are its complete operation.
const fn dependency_only_action() -> Action {
    Action {
        recipe: Recipe::Command {
            command: StringOrList::Empty,
        },
        description: None,
        depfile: None,
        deps_format: None,
        pool: None,
        restat: false,
    }
}
fn edge(
    action_id: &str,
    output: &str,
    deps: &[&str],
    dependency_order: DependencyOrder,
) -> BuildEdge {
    BuildEdge {
        action_id: action_id.into(),
        inputs: Vec::new(),
        implicit_deps: deps.iter().map(Utf8PathBuf::from).collect(),
        dependency_order,
        explicit_outputs: vec![Utf8PathBuf::from(output)],
        implicit_outputs: Vec::new(),
        order_only_deps: Vec::new(),
        phony: false,
        always: false,
    }
}

fn serial_order_graph() -> BuildGraph {
    let mut graph = BuildGraph::default();
    for (name, command) in [
        (
            "fmt",
            "test ! -e check-fmt && echo one >> order.log && touch check-fmt",
        ),
        (
            "lint",
            "test -e check-fmt && test ! -e lint && echo two >> order.log && touch lint",
        ),
        (
            "test",
            "test -e lint && test ! -e test && echo three >> order.log && touch test",
        ),
    ] {
        graph.actions.insert(name.into(), action(command));
    }
    graph.actions.insert("all".into(), dependency_only_action());
    for (action_id, output, deps, dependency_order) in [
        ("fmt", "check-fmt", &[][..], DependencyOrder::Parallel),
        ("lint", "lint", &[][..], DependencyOrder::Parallel),
        ("test", "test", &[][..], DependencyOrder::Parallel),
        (
            "all",
            "all",
            &["check-fmt", "lint", "test"][..],
            DependencyOrder::Serial,
        ),
    ] {
        graph.targets.insert(
            Utf8PathBuf::from(output),
            edge(action_id, output, deps, dependency_order),
        );
    }
    graph
}

fn shared_work_graph() -> BuildGraph {
    let mut graph = BuildGraph::default();
    for (name, command) in [
        (
            "shared",
            "i=0; while test ! -f unrelated-start; do i=$((i + 1)); test \"$i\" -lt 100 || exit 1; sleep 0.01; done; test ! -f unrelated-end || exit 1; echo shared >> execution.log; touch shared",
        ),
        ("left", "test -f shared && touch left"),
        ("right", "test -f shared && touch right"),
        (
            "unrelated",
            "touch unrelated-start; sleep 0.2; touch unrelated-end; touch unrelated",
        ),
        ("all", "touch all"),
    ] {
        graph.actions.insert(name.into(), action(command));
    }
    for (action_id, output, deps, dependency_order) in [
        ("shared", "shared", &[][..], DependencyOrder::Parallel),
        ("left", "left", &[][..], DependencyOrder::Parallel),
        ("right", "right", &[][..], DependencyOrder::Parallel),
        (
            "left",
            "left-final",
            &["shared", "left"][..],
            DependencyOrder::Serial,
        ),
        (
            "right",
            "right-final",
            &["shared", "right"][..],
            DependencyOrder::Serial,
        ),
        ("unrelated", "unrelated", &[][..], DependencyOrder::Parallel),
        (
            "all",
            "all",
            &["left-final", "right-final", "unrelated"][..],
            DependencyOrder::Parallel,
        ),
    ] {
        graph.targets.insert(
            Utf8PathBuf::from(output),
            edge(action_id, output, deps, dependency_order),
        );
    }
    graph
}

/// Write a bundle into `dir` (sidecars beneath `.netsuke/dyndep`) and return
/// the main build file path.
fn stage_bundle(dir: &TempDir, bundle: &netsuke::ninja_gen::GeneratedNinja) -> Result<Utf8PathBuf> {
    let root = Utf8PathBuf::from_path_buf(dir.path().to_path_buf()).map_err(|path| {
        anyhow::anyhow!("temporary Ninja directory is not UTF-8: {}", path.display())
    })?;
    let root_dir = Dir::open_ambient_dir(&root, ambient_authority())
        .context("open temporary Ninja directory")?;
    for dd in bundle.dyndep_files() {
        if let Some(parent) = dd.relative_path().parent() {
            root_dir
                .create_dir_all(parent)
                .with_context(|| format!("create sidecar dir {parent}"))?;
        }
        root_dir
            .write(dd.relative_path(), dd.content())
            .with_context(|| format!("write sidecar {}", dd.relative_path()))?;
    }
    root_dir
        .write("build.ninja", bundle.build_file())
        .context("write main ninja file")?;
    Ok(root.join("build.ninja"))
}

fn run_ninja(dir: &TempDir, main: &Utf8PathBuf) -> Result<std::process::Output> {
    run_ninja_with_jobs(dir, main, 1)
}

fn run_ninja_with_jobs(
    dir: &TempDir,
    main: &Utf8PathBuf,
    jobs: u8,
) -> Result<std::process::Output> {
    Command::new(NINJA)
        .arg("-C")
        .arg(dir.path())
        .arg("-f")
        .arg(main.as_str())
        .arg("-j")
        .arg(jobs.to_string())
        .arg("all")
        .output()
        .map_err(|error| {
            if error.kind() == ErrorKind::NotFound {
                anyhow::anyhow!("ninja must be available on PATH to run serial dependency tests")
            } else {
                error.into()
            }
        })
        .context("spawn ninja")
}

struct SuccessfulNinjaRun {
    _directory: TempDir,
    root: Dir,
}

fn run_successful_graph(graph: &BuildGraph, jobs: u8) -> Result<SuccessfulNinjaRun> {
    let directory = tempfile::tempdir()?;
    let bundle = generate_bundle(graph)?;
    let main = stage_bundle(&directory, &bundle)?;
    let output = run_ninja_with_jobs(&directory, &main, jobs)?;
    ensure!(
        output.status.success(),
        "ninja failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let root_path = Utf8PathBuf::from_path_buf(directory.path().to_path_buf()).map_err(|path| {
        anyhow::anyhow!("temporary Ninja directory is not UTF-8: {}", path.display())
    })?;
    let root = Dir::open_ambient_dir(&root_path, ambient_authority())
        .context("open temporary Ninja directory")?;
    Ok(SuccessfulNinjaRun {
        _directory: directory,
        root,
    })
}

#[test]
fn serial_deps_run_in_declaration_order() -> Result<()> {
    let run = run_successful_graph(&serial_order_graph(), 3)?;
    let log = run
        .root
        .read_to_string("order.log")
        .context("read order log")?;
    ensure!(
        log.lines().collect::<Vec<_>>() == vec!["one", "two", "three"],
        "deps ran out of order: {log:?}"
    );
    ensure!(
        run.root.open("all").is_err(),
        "dependency-only aggregate must not run a synthetic recipe"
    );
    Ok(())
}

#[test]
fn failure_of_early_dep_stops_later_stages() -> Result<()> {
    let dir = tempfile::tempdir()?;
    let mut graph = BuildGraph::default();
    graph.actions.insert("fail".into(), action("exit 1"));
    graph
        .actions
        .insert("later".into(), action("touch later-marker"));
    graph.actions.insert("all".into(), dependency_only_action());

    graph.targets.insert(
        Utf8PathBuf::from("first"),
        BuildEdge {
            action_id: "fail".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("first")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("second"),
        BuildEdge {
            action_id: "later".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("second")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("all"),
        BuildEdge {
            action_id: "all".into(),
            inputs: Vec::new(),
            implicit_deps: vec!["first".into(), "second".into()],
            dependency_order: DependencyOrder::Serial,
            explicit_outputs: vec![Utf8PathBuf::from("all")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );

    let bundle = generate_bundle(&graph)?;
    let main = stage_bundle(&dir, &bundle)?;
    let out = run_ninja(&dir, &main)?;
    ensure!(
        !out.status.success(),
        "ninja should fail when the first dep fails"
    );
    ensure!(
        !dir.path().join("later-marker").exists(),
        "later dependency must not run after the first dep fails"
    );
    Ok(())
}

#[test]
fn shared_serial_work_runs_once_while_unrelated_work_progresses() -> Result<()> {
    let run = run_successful_graph(&shared_work_graph(), 3)?;
    let executions = run
        .root
        .read_to_string("execution.log")
        .context("read shared-work log")?;
    ensure!(
        executions.lines().collect::<Vec<_>>() == ["shared"],
        "shared work must execute once: {executions:?}"
    );
    ensure!(
        run.root.open("all").is_ok(),
        "aggregate must finish after serial consumers and unrelated work"
    );
    Ok(())
}
