//! Real-Ninja runtime tests for serial dependency ordering.
//!
//! These tests drive an actual `ninja` process against a bundle generated by
//! `generate_bundle`, using filesystem markers to prove declaration order,
//! failure short-circuiting, and shared-work reuse. They deliberately assert
//! observable behaviour rather than generated text.

use anyhow::{Context, Result, ensure};
use camino::Utf8PathBuf;
use cap_std::{ambient_authority, fs_utf8::Dir};
use netsuke::ast::{DependencyOrder, Recipe};
use netsuke::ir::{Action, BuildEdge, BuildGraph};
use netsuke::ninja_gen::generate_bundle;
use std::process::Command;
use tempfile::TempDir;

const NINJA: &str = "ninja";

fn action(command: &str) -> Action {
    Action {
        recipe: Recipe::Command {
            command: command.into(),
        },
        description: None,
        depfile: None,
        deps_format: None,
        pool: None,
        restat: false,
    }
}

fn edge(
    action_id: &str,
    output: &str,
    deps: &[&str],
    dependency_order: DependencyOrder,
) -> BuildEdge {
    BuildEdge {
        action_id: action_id.into(),
        inputs: Vec::new(),
        implicit_deps: deps.iter().map(Utf8PathBuf::from).collect(),
        dependency_order,
        explicit_outputs: vec![Utf8PathBuf::from(output)],
        implicit_outputs: Vec::new(),
        order_only_deps: Vec::new(),
        phony: false,
        always: false,
    }
}

fn serial_order_graph() -> BuildGraph {
    let mut graph = BuildGraph::default();
    for (name, command) in [
        ("fmt", "echo one >> order.log"),
        ("lint", "echo two >> order.log"),
        ("test", "echo three >> order.log"),
        ("all", "echo all >> order.log"),
    ] {
        graph.actions.insert(name.into(), action(command));
    }
    for (action_id, output, deps, dependency_order) in [
        ("fmt", "check-fmt", &[][..], DependencyOrder::Parallel),
        ("lint", "lint", &[][..], DependencyOrder::Parallel),
        ("test", "test", &[][..], DependencyOrder::Parallel),
        (
            "all",
            "all",
            &["check-fmt", "lint", "test"][..],
            DependencyOrder::Serial,
        ),
    ] {
        graph.targets.insert(
            Utf8PathBuf::from(output),
            edge(action_id, output, deps, dependency_order),
        );
    }
    graph
}

/// Write a bundle into `dir` (sidecars beneath `.netsuke/dyndep`) and return
/// the main build file path.
fn stage_bundle(dir: &TempDir, bundle: &netsuke::ninja_gen::GeneratedNinja) -> Result<Utf8PathBuf> {
    let root = Utf8PathBuf::from_path_buf(dir.path().to_path_buf()).map_err(|path| {
        anyhow::anyhow!("temporary Ninja directory is not UTF-8: {}", path.display())
    })?;
    let root_dir = Dir::open_ambient_dir(&root, ambient_authority())
        .context("open temporary Ninja directory")?;
    for dd in bundle.dyndep_files() {
        if let Some(parent) = dd.relative_path().parent() {
            root_dir
                .create_dir_all(parent)
                .with_context(|| format!("create sidecar dir {parent}"))?;
        }
        root_dir
            .write(dd.relative_path(), dd.content())
            .with_context(|| format!("write sidecar {}", dd.relative_path()))?;
    }
    root_dir
        .write("build.ninja", bundle.build_file())
        .context("write main ninja file")?;
    Ok(root.join("build.ninja"))
}

fn run_ninja(dir: &TempDir, main: &Utf8PathBuf) -> Result<std::process::Output> {
    Command::new(NINJA)
        .arg("-C")
        .arg(dir.path())
        .arg("-f")
        .arg(main.as_str())
        .arg("all")
        .output()
        .context("spawn ninja")
}

#[test]
fn serial_deps_run_in_declaration_order() -> Result<()> {
    let dir = tempfile::tempdir()?;
    let bundle = generate_bundle(&serial_order_graph())?;
    let main = stage_bundle(&dir, &bundle)?;
    let out = run_ninja(&dir, &main)?;
    ensure!(
        out.status.success(),
        "ninja failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let root_path = Utf8PathBuf::from_path_buf(dir.path().to_path_buf()).map_err(|path| {
        anyhow::anyhow!("temporary Ninja directory is not UTF-8: {}", path.display())
    })?;
    let root = Dir::open_ambient_dir(&root_path, ambient_authority())
        .context("open temporary Ninja directory")?;
    let log = root.read_to_string("order.log").context("read order log")?;
    ensure!(
        log.lines().collect::<Vec<_>>() == vec!["one", "two", "three", "all"],
        "deps ran out of order: {log:?}"
    );
    Ok(())
}

#[test]
fn failure_of_early_dep_stops_later_stages() -> Result<()> {
    let dir = tempfile::tempdir()?;
    let mut graph = BuildGraph::default();
    graph.actions.insert("fail".into(), action("exit 1"));
    graph
        .actions
        .insert("later".into(), action("touch later-marker"));
    graph
        .actions
        .insert("all".into(), action("touch all-marker"));

    graph.targets.insert(
        Utf8PathBuf::from("first"),
        BuildEdge {
            action_id: "fail".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("first")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("second"),
        BuildEdge {
            action_id: "later".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("second")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("all"),
        BuildEdge {
            action_id: "all".into(),
            inputs: Vec::new(),
            implicit_deps: vec!["first".into(), "second".into()],
            dependency_order: DependencyOrder::Serial,
            explicit_outputs: vec![Utf8PathBuf::from("all")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );

    let bundle = generate_bundle(&graph)?;
    let main = stage_bundle(&dir, &bundle)?;
    let out = run_ninja(&dir, &main)?;
    ensure!(
        !out.status.success(),
        "ninja should fail when the first dep fails"
    );
    ensure!(
        !dir.path().join("later-marker").exists(),
        "later dependency must not run after the first dep fails"
    );
    ensure!(
        !dir.path().join("all-marker").exists(),
        "aggregate must not run after the first dep fails"
    );
    Ok(())
}
