//! Real-Ninja runtime tests for serial dependency ordering.
//!
//! These tests drive an actual `ninja` process against a bundle generated by
//! `generate_bundle`, using filesystem markers to prove declaration order,
//! failure short-circuiting, and shared-work reuse. They deliberately assert
//! observable behaviour rather than generated text.

use anyhow::{Context, Result, ensure};
use camino::Utf8PathBuf;
use netsuke::ast::{DependencyOrder, Recipe};
use netsuke::ir::{Action, BuildEdge, BuildGraph};
use netsuke::ninja_gen::generate_bundle;
use std::process::Command;
use tempfile::TempDir;

const NINJA: &str = "ninja";

fn action(command: &str) -> Action {
    Action {
        recipe: Recipe::Command {
            command: command.into(),
        },
        description: None,
        depfile: None,
        deps_format: None,
        pool: None,
        restat: false,
    }
}

fn edge(output: &str, deps: &[&str], order: DependencyOrder) -> BuildEdge {
    let implicit_deps: Vec<_> = deps.iter().map(Utf8PathBuf::from).collect();
    BuildEdge {
        action_id: "dep-rule".into(),
        inputs: Vec::new(),
        implicit_deps,
        dependency_order: order,
        explicit_outputs: vec![Utf8PathBuf::from(output)],
        implicit_outputs: Vec::new(),
        order_only_deps: Vec::new(),
        phony: false,
        always: false,
    }
}

/// Write a bundle into `dir` (sidecars beneath `.netsuke/dyndep`) and return
/// the main build file path.
fn stage_bundle(dir: &TempDir, bundle: &netsuke::ninja_gen::GeneratedNinja) -> Result<Utf8PathBuf> {
    for dd in bundle.dyndep_files() {
        let path = dir.path().join(dd.relative_path());
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create sidecar dir {}", parent.display()))?;
        }
        std::fs::write(&path, dd.content())
            .with_context(|| format!("write sidecar {}", path.display()))?;
    }
    let main = dir.path().join("build.ninja");
    std::fs::write(&main, bundle.build_file()).context("write main ninja file")?;
    Utf8PathBuf::from_path_buf(main).map_err(|_| anyhow::anyhow!("main path utf8"))
}

fn run_ninja(dir: &TempDir, main: &Utf8PathBuf) -> Result<std::process::Output> {
    Command::new(NINJA)
        .arg("-C")
        .arg(dir.path())
        .arg("-f")
        .arg(main.as_str())
        .arg("all")
        .output()
        .context("spawn ninja")
}

#[test]
fn serial_deps_run_in_declaration_order() -> Result<()> {
    let dir = tempfile::tempdir()?;
    let mut graph = BuildGraph::default();

    graph
        .actions
        .insert("fmt".into(), action("echo one >> order.log"));
    graph
        .actions
        .insert("lint".into(), action("echo two >> order.log"));
    graph
        .actions
        .insert("test".into(), action("echo three >> order.log"));
    graph
        .actions
        .insert("all".into(), action("echo all >> order.log"));

    graph.targets.insert(
        Utf8PathBuf::from("check-fmt"),
        BuildEdge {
            action_id: "fmt".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("check-fmt")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("lint"),
        BuildEdge {
            action_id: "lint".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("lint")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("test"),
        BuildEdge {
            action_id: "test".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("test")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("all"),
        BuildEdge {
            action_id: "all".into(),
            inputs: Vec::new(),
            implicit_deps: vec!["check-fmt".into(), "lint".into(), "test".into()],
            dependency_order: DependencyOrder::Serial,
            explicit_outputs: vec![Utf8PathBuf::from("all")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );

    let bundle = generate_bundle(&graph)?;
    let main = stage_bundle(&dir, &bundle)?;
    let out = run_ninja(&dir, &main)?;
    ensure!(
        out.status.success(),
        "ninja failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let log = std::fs::read_to_string(dir.path().join("order.log"))?;
    ensure!(
        log.lines().collect::<Vec<_>>() == vec!["one", "two", "three", "all"],
        "deps ran out of order: {log:?}"
    );
    Ok(())
}

#[test]
fn failure_of_early_dep_stops_later_stages() -> Result<()> {
    let dir = tempfile::tempdir()?;
    let mut graph = BuildGraph::default();
    graph.actions.insert("fail".into(), action("exit 1"));
    graph
        .actions
        .insert("later".into(), action("touch later-marker"));
    graph
        .actions
        .insert("all".into(), action("touch all-marker"));

    graph.targets.insert(
        Utf8PathBuf::from("first"),
        BuildEdge {
            action_id: "fail".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("first")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("second"),
        BuildEdge {
            action_id: "later".into(),
            inputs: Vec::new(),
            implicit_deps: Vec::new(),
            dependency_order: DependencyOrder::Parallel,
            explicit_outputs: vec![Utf8PathBuf::from("second")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );
    graph.targets.insert(
        Utf8PathBuf::from("all"),
        BuildEdge {
            action_id: "all".into(),
            inputs: Vec::new(),
            implicit_deps: vec!["first".into(), "second".into()],
            dependency_order: DependencyOrder::Serial,
            explicit_outputs: vec![Utf8PathBuf::from("all")],
            implicit_outputs: Vec::new(),
            order_only_deps: Vec::new(),
            phony: false,
            always: false,
        },
    );

    let bundle = generate_bundle(&graph)?;
    let main = stage_bundle(&dir, &bundle)?;
    let out = run_ninja(&dir, &main)?;
    ensure!(
        !out.status.success(),
        "ninja should fail when the first dep fails"
    );
    ensure!(
        !dir.path().join("later-marker").exists(),
        "later dependency must not run after the first dep fails"
    );
    ensure!(
        !dir.path().join("all-marker").exists(),
        "aggregate must not run after the first dep fails"
    );
    Ok(())
}
