[package]
name = "test_support"
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[dependencies]
tempfile = "3.8.0"
mockable = { version = "0.3", features = ["mock"] }
ninja_env = { path = "../ninja_env" }
miette = "7.6.0"

[dev-dependencies]
rstest = "0.18.0"
