---
name: Release Dry Run

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      publish: false
    secrets: inherit

  validate-artifacts:
    name: Validate packaged artefacts
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artefacts
        uses: >-
          actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        # v4
        with:
          path: dist
          pattern: ${{ env.REPO_NAME }}-*
      - name: Ensure artefacts exist
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          mapfile -t files < <(find dist -type f)
          if [ "${#files[@]}" -eq 0 ]; then
            echo '::error title=Missing artefacts::No artefacts downloaded'
            exit 1
          fi
          printf 'Found %s artefact(s) in dist/\n' "${#files[@]}"
