---
name: Release Dry Run

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      dry-run: true
    secrets: inherit
